### ISSUE TITLE
Problem with reading Navpt

### ISSUE THREAD

**Issue by masoudr** [loginov-rocks/UbxGps#4]
Hi,
I'm using the Ublox 7m module. I'm using this library and it has no problem. But every time I power up the module I need to upload `Auto-configuration-mega.ino` first and then I am able to upload `Navpt` example and receive the coordinates, But when I restart the module the `gps.read()` has no value and I should re-upload config sample again. Is there any fix for this?
Thanks.

**Comment by loginov-rocks** [comment]
Hi, @masoudr!

Unfortunatelly, these ublox modules are configured from the factory to reset its settings when the power off. That's why there is a battery on the breakout board, it should be charged. You can find more about it in the docs [here](https://github.com/1oginov/UBX-GPS-Library/raw/master/Docs/u-blox%207%20Receiver%20Description%20Including%20Protocol%20Specification%20V14.pdf) (section _8 Receiver Configuration_).

I faced with the issue and it took a while to find how to deal with it, but the only thing we can do is to connect the module to the power supply. I created the auto configuration sketch to ease the process. So if you want to make autonomous device, you can integrate the auto configuration to the setup process of your microcontroller.
