### ISSUE TITLE
saving ubx data for conversion to rinex file format for post processing

### ISSUE THREAD

**Issue by rikaad** [loginov-rocks/UbxGps#9]
HI,
Can your library be used to obtain raw GPS data (which would be stored on an SD card as a .ubx file) for later conversion to the Rinex format for post processing. If so would using UbxGpsNavPvt be the best option? We are looking to accurately track animal movements in remote environments.

Any help is much appreciated.

Regards

**Comment by loginov-rocks** [comment]
Hello, @rikaad !

Does `.ubx` file contain raw binary data coming from the GPS? If so, I think you don't need this library, since it parses binary stream, it's just an overhead. You just only need to put everything coming from UART to a file and that's it :)

I don't know much about Rinex format, how it looks like and what data does it use?

**Comment by rikaad** [comment]
Hi Danila,
Thanks for the reply.

I am a little bit new to this but It is my understanding that a normal GPS outputs NMEA sentences as default data format and therefore it requires a special command to put the unit into raw binary data output mode. Is this correct?
The following is taken from Wikipedia;
Receiver Independent Exchange Format (RINEX) is a data interchange format for raw satellite navigation system<https://en.wikipedia.org/wiki/Global_navigation_satellite_system> data. This allows the user to post-process the received data to produce a more accurate result — usually with other data unknown to the original receiver, such as better models of the atmospheric conditions at time of measurement.
The final output of a navigation receiver is usually its position, speed or other related physical quantities. However, the calculation of these quantities are based on a series of measurements from one or more satellite constellations. Although receivers calculate positions in real time, in many cases it is interesting to store intermediate measures for later use. RINEX is the standard format that allows the management and disposal of the measures generated by a receiver, as well as their off-line processing by a multitude of applications, whatever the manufacturer of both the receiver and the computer application.

Any  help is much appreciated.

Cheers.

**Comment by loginov-rocks** [comment]
NMEA uses ASCII, while UBX is a binary protocol. By default u-blox modules outputs NMEA and should be configured to output UBX, please refer to [GPS module configuration](https://github.com/1oginov/UbxGps#gps-module-configuration) in the readme.

Actually, I have already read about Rinex in the Wikipedia, but haven't found anything technical or related to your questions, that's why I'm asking you.

**Comment by loginov-rocks** [comment]
Closing, since a month has passed
